from __future__ import annotations

import re
from pathlib import Path

from .dedup import deduplicate_lines
from .fingerprint import encode_fingerprint, fingerprint_repo
from .types import CommandFact, ConventionFact, ScanResult, StackFact

SECTION_ORDER = ("stack", "commands", "testing", "conventions", "boundaries", "security")
START_RE = r"<!-- agents-md:start:{name} -->"
END_RE = r"<!-- agents-md:end:{name} -->"


def render_document(scan: ScanResult, *, no_dedup: bool = False) -> str:
    sections = render_sections(scan, no_dedup=no_dedup)
    lines = [
        "# AGENTS.md",
        "",
        "Generated by `agents-md`. Keep manual notes outside managed sections so `agents-md update` can preserve them.",
        "",
    ]
    for name in SECTION_ORDER:
        lines.extend(_wrap_section(name, sections[name]))
        lines.append("")
    if scan.monorepo:
        lines.extend(
            [
                "<!-- agents-md:start:monorepo -->",
                "## Monorepo Note",
                "- See individual package directories for package-specific instructions (not yet configured).",
                "<!-- agents-md:end:monorepo -->",
                "",
            ]
        )
    lines.append(encode_fingerprint(fingerprint_repo(scan.root)))
    return "\n".join(lines).rstrip() + "\n"


def render_sections(scan: ScanResult, *, no_dedup: bool = False) -> dict[str, list[str]]:
    sections = {
        "stack": _stack_section(scan.stack),
        "commands": _commands_section(scan.commands),
        "testing": _testing_section(scan.commands),
        "conventions": _conventions_section(scan.conventions),
        "boundaries": _boundaries_section(scan),
        "security": _security_section(),
    }
    if not no_dedup:
        facts = getattr(scan, "_markdown_facts", set())
        for name, lines in list(sections.items()):
            if name in {"boundaries", "security"}:
                continue
            sections[name] = deduplicate_lines(lines, facts, scan.dedup)
    return sections


def replace_managed_sections(existing: str, new_sections: dict[str, list[str]]) -> tuple[str, list[str]]:
    changed: list[str] = []
    updated = existing
    for name in SECTION_ORDER:
        pattern = re.compile(
            rf"<!-- agents-md:start:{re.escape(name)} -->.*?<!-- agents-md:end:{re.escape(name)} -->",
            re.DOTALL,
        )
        replacement = "\n".join(_wrap_section(name, new_sections[name]))
        if not pattern.search(updated):
            continue
        before = updated
        updated = pattern.sub(replacement, updated)
        if updated != before:
            changed.append(name)
    return updated, changed


def has_managed_sections(text: str) -> bool:
    return "<!-- agents-md:start:" in text and "<!-- agents-md:end:" in text


def line_count(text: str) -> int:
    return len(text.splitlines())


def _wrap_section(name: str, lines: list[str]) -> list[str]:
    return [START_RE.format(name=name), *lines, END_RE.format(name=name)]


def _stack_section(stack: list[StackFact]) -> list[str]:
    lines = ["## Stack"]
    if not stack:
        return lines + ["- No high-confidence stack facts detected."]
    grouped: dict[str, list[StackFact]] = {}
    for fact in stack:
        grouped.setdefault(fact.kind, []).append(fact)
    for kind in sorted(grouped):
        labels = sorted({fact.label() for fact in grouped[kind]})
        lines.append(f"- {kind.replace('-', ' ').title()}: {', '.join(labels)}")
    return lines


def _commands_section(commands: list[CommandFact]) -> list[str]:
    lines = ["## Commands"]
    selected = _select_commands(commands, include_single=False)
    if not selected:
        return lines + ["- No high-confidence project commands detected. Add exact commands manually before relying on this file."]
    for command in selected:
        note = f" ({command.note})" if command.note and len(command.note) <= 80 else ""
        warning = " Ask first before running." if command.risky else ""
        lines.append(f"- {command.category}: `{command.command}` from {command.source}.{warning}{note}")
    return lines


def _testing_section(commands: list[CommandFact]) -> list[str]:
    lines = ["## Testing"]
    full = next((cmd for cmd in commands if cmd.category == "test"), None)
    single = next((cmd for cmd in commands if cmd.category == "single-test"), None)
    if full:
        lines.append(f"- Full suite: `{full.command}`")
    else:
        lines.append("- Full suite: add the exact command after the test runner is confirmed.")
    if single:
        lines.append(f"- Single test: `{single.command}`")
    else:
        lines.append("- Single test: add a file/function-targeted command; avoid running only the full suite for small edits.")
    lines.append("- Prefer the narrowest relevant test while iterating, then run the broader check before release changes.")
    return lines


def _conventions_section(conventions: list[ConventionFact]) -> list[str]:
    lines = ["## Conventions"]
    if not conventions:
        return lines + ["- No counterintuitive repo-specific conventions detected; avoid adding generic style rules here."]
    for convention in conventions[:8]:
        lines.append(f"- {convention.text} ({convention.source})")
    return lines


def _boundaries_section(scan: ScanResult) -> list[str]:
    risky = [cmd for cmd in scan.commands if cmd.risky or cmd.category == "migration"]
    ask_first = [
        f"- Ask before running `{command.command}` because it appears to touch migrations or data." for command in risky[:5]
    ]
    ask_first.append(
        "- Ask before deleting files, rewriting public history, changing release/package metadata, or running commands that mutate databases/infrastructure."
    )
    return [
        "## Boundaries",
        "### Always Do",
        "- Run the narrowest relevant test before handing off a code change.",
        "### Ask First",
        *ask_first,
        "### Never Do",
        "- Never commit secrets, tokens, or `.env` files.",
        "- Never overwrite a hand-written AGENTS.md without `--force` or an explicit confirmation.",
        "- Never modify `vendor/` unless the user explicitly asks.",
    ]


def _security_section() -> list[str]:
    return [
        "## Security",
        "- Treat API keys as environment-only configuration; do not write them into AGENTS.md or generated logs.",
        "- Prefer `--no-llm` in CI unless a provider key is intentionally configured for synthesis.",
        "- Review generated files before publishing because AGENTS.md is meant to guide automated agents.",
    ]


def _select_commands(commands: list[CommandFact], *, include_single: bool) -> list[CommandFact]:
    priority = ["install", "run", "build", "lint", "typecheck", "test", "migration"]
    if include_single:
        priority.append("single-test")
    selected: list[CommandFact] = []
    seen: set[tuple[str, str]] = set()
    for category in priority:
        for command in commands:
            key = (command.category, command.command)
            if command.category == category and key not in seen:
                selected.append(command)
                seen.add(key)
                break
    return selected
